# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addAdmin.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from database import Database
import hashlib

database = Database()

class Ui_AddAdminWindow(object):
    def setupUi(self, AddAdminWindow):
        AddAdminWindow.setObjectName("AddAdminWindow")
        AddAdminWindow.resize(800, 600)
        AddAdminWindow.setMinimumSize(QtCore.QSize(800, 600))
        AddAdminWindow.setMaximumSize(QtCore.QSize(800, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/fugue-icons-3.5.6/icons/user--plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AddAdminWindow.setWindowIcon(icon)
        AddAdminWindow.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"font-weight:bold")
        self.centralwidget = QtWidgets.QWidget(AddAdminWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 24, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.submitStatusLabel = QtWidgets.QLabel(self.centralwidget)
        self.submitStatusLabel.setStyleSheet("padding-left:32px")
        self.submitStatusLabel.setText("Fill in details to add a new admin...\n* ---> required")
        self.submitStatusLabel.setObjectName("submitStatusLabel")
        self.verticalLayout_4.addWidget(self.submitStatusLabel)
        self.verticalLayout.addLayout(self.verticalLayout_4)
        spacerItem1 = QtWidgets.QSpacerItem(20, 32, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem1)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.firstNameLabel = QtWidgets.QLabel(self.widget)
        self.firstNameLabel.setObjectName("firstNameLabel")
        self.verticalLayout_3.addWidget(self.firstNameLabel)
        self.firstNameField = QtWidgets.QLineEdit(self.widget)
        self.firstNameField.setStyleSheet("QLineEdit{\n"
"border: 4px solid;\n"
"border-color: rgb(85, 85, 255);\n"
"border-radius: 8px;\n"
"padding:4px;\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"border-bottom-color: rgb(0, 255, 255);\n"
"}")
        self.firstNameField.setMaxLength(26)
        self.firstNameField.setObjectName("firstNameField")
        self.verticalLayout_3.addWidget(self.firstNameField)
        self.secondNameLabel = QtWidgets.QLabel(self.widget)
        self.secondNameLabel.setObjectName("secondNameLabel")
        self.verticalLayout_3.addWidget(self.secondNameLabel)
        self.secondNameField = QtWidgets.QLineEdit(self.widget)
        self.secondNameField.setStyleSheet("QLineEdit{\n"
"border: 4px solid;\n"
"border-color: rgb(85, 85, 255);\n"
"border-radius: 8px;\n"
"padding:4px;\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"border-bottom-color: rgb(0, 255, 255);\n"
"}")
        self.secondNameField.setMaxLength(26)
        self.secondNameField.setObjectName("secondNameField")
        self.verticalLayout_3.addWidget(self.secondNameField)
        self.lastNameLabel = QtWidgets.QLabel(self.widget)
        self.lastNameLabel.setObjectName("lastNameLabel")
        self.verticalLayout_3.addWidget(self.lastNameLabel)
        self.lastNameField = QtWidgets.QLineEdit(self.widget)
        self.lastNameField.setStyleSheet("QLineEdit{\n"
"border: 4px solid;\n"
"border-color: rgb(85, 85, 255);\n"
"border-radius: 8px;\n"
"padding:4px;\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"border-bottom-color: rgb(0, 255, 255);\n"
"}")
        self.lastNameField.setMaxLength(26)
        self.lastNameField.setObjectName("lastNameField")
        self.verticalLayout_3.addWidget(self.lastNameField)
        self.statusLabel = QtWidgets.QLabel(self.widget)
        self.statusLabel.setObjectName("statusLabel")
        self.verticalLayout_3.addWidget(self.statusLabel)
        self.statusField = QtWidgets.QLineEdit(self.widget)
        self.statusField.setStyleSheet("QLineEdit{\n"
"border: 4px solid;\n"
"border-color: rgb(85, 85, 255);\n"
"border-radius: 8px;\n"
"padding:4px;\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"border-bottom-color: rgb(0, 255, 255);\n"
"}")
        self.statusField.setMaxLength(26)
        self.statusField.setObjectName("statusField")
        self.verticalLayout_3.addWidget(self.statusField)
        self.positionLabel = QtWidgets.QLabel(self.widget)
        self.positionLabel.setObjectName("positionLabel")
        self.verticalLayout_3.addWidget(self.positionLabel)
        self.positionField = QtWidgets.QLineEdit(self.widget)
        self.positionField.setStyleSheet("QLineEdit{\n"
"border: 4px solid;\n"
"border-color: rgb(85, 85, 255);\n"
"border-radius: 8px;\n"
"padding:4px;\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"border-bottom-color: rgb(0, 255, 255);\n"
"}")
        self.positionField.setMaxLength(26)
        self.positionField.setObjectName("positionField")
        self.verticalLayout_3.addWidget(self.positionField)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        spacerItem4 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.staffNumberLabel = QtWidgets.QLabel(self.widget)
        self.staffNumberLabel.setObjectName("staffNumberLabel")
        self.verticalLayout_2.addWidget(self.staffNumberLabel)
        self.staffNumberField = QtWidgets.QLineEdit(self.widget)
        self.staffNumberField.setStyleSheet("QLineEdit{\n"
"border: 4px solid;\n"
"border-color: rgb(85, 85, 255);\n"
"border-radius: 8px;\n"
"padding:4px;\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"border-bottom-color: rgb(0, 255, 255);\n"
"}")
        self.staffNumberField.setMaxLength(26)
        self.staffNumberField.setObjectName("staffNumberField")
        self.verticalLayout_2.addWidget(self.staffNumberField)
        self.passwordLabel = QtWidgets.QLabel(self.widget)
        self.passwordLabel.setObjectName("passwordLabel")
        self.verticalLayout_2.addWidget(self.passwordLabel)
        self.passwordField = QtWidgets.QLineEdit(self.widget)
        self.passwordField.setStyleSheet("QLineEdit{\n"
"border: 4px solid;\n"
"border-color: rgb(85, 85, 255);\n"
"border-radius: 8px;\n"
"padding:4px;\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"border-bottom-color: rgb(0, 255, 255);\n"
"}")
        self.passwordField.setMaxLength(26)
        self.passwordField.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordField.setObjectName("passwordField")
        self.verticalLayout_2.addWidget(self.passwordField)
        self.repeatPasswordLabel = QtWidgets.QLabel(self.widget)
        self.repeatPasswordLabel.setObjectName("repeatPasswordLabel")
        self.verticalLayout_2.addWidget(self.repeatPasswordLabel)
        self.repeatPasswordField = QtWidgets.QLineEdit(self.widget)
        self.repeatPasswordField.setStyleSheet("QLineEdit{\n"
"border: 4px solid;\n"
"border-color: rgb(85, 85, 255);\n"
"border-radius: 8px;\n"
"padding:4px;\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"border-bottom-color: rgb(0, 255, 255);\n"
"}")
        self.repeatPasswordField.setMaxLength(26)
        self.repeatPasswordField.setEchoMode(QtWidgets.QLineEdit.Password)
        self.repeatPasswordField.setObjectName("repeatPasswordField")
        self.verticalLayout_2.addWidget(self.repeatPasswordField)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.clearButton = QtWidgets.QPushButton(self.widget)
        self.clearButton.setMinimumSize(QtCore.QSize(80, 0))
        self.clearButton.setStyleSheet("QPushButton{\n"
"border: 2px solid;\n"
"color:rgb(0, 0, 0);\n"
"border-color: rgb(136, 23, 152);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 8px;\n"
"padding: 4px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color: rgb(1, 18, 255);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(0, 0, 0);\n"
"}\n"
"")
        self.clearButton.setObjectName("clearButton")
        self.horizontalLayout_3.addWidget(self.clearButton, 0, QtCore.Qt.AlignRight)
        self.addAdminButton = QtWidgets.QPushButton(self.widget)
        self.addAdminButton.setMinimumSize(QtCore.QSize(80, 0))
        self.addAdminButton.setStyleSheet("QPushButton{\n"
"border: 2px solid;\n"
"color:rgb(0, 0, 0);\n"
"border-color: rgb(136, 23, 152);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 8px;\n"
"padding: 4px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color: rgb(1, 18, 255);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(0, 0, 0);\n"
"}\n"
"")
        self.addAdminButton.setObjectName("addAdminButton")
        self.horizontalLayout_3.addWidget(self.addAdminButton, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.verticalLayout.addWidget(self.widget)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem7)
        AddAdminWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AddAdminWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        AddAdminWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AddAdminWindow)
        self.statusbar.setObjectName("statusbar")
        AddAdminWindow.setStatusBar(self.statusbar)

        self.retranslateUi(AddAdminWindow)
        self.clearButton.clicked.connect(self.clear_fields) # type: ignore
        self.addAdminButton.clicked.connect(self.validate_data)
        QtCore.QMetaObject.connectSlotsByName(AddAdminWindow)
    def clear_fields(self):
        '''clears data from the fields'''
        self.passwordField.clear()
        self.statusField.clear()
        self.firstNameField.clear()
        self.staffNumberField.clear()
        self.secondNameField.clear()
        self.lastNameField.clear()
        self.positionField.clear()
        self.submitStatusLabel.clear()
        self.submitStatusLabel.setStyleSheet("padding-left:32px;""color:rgb(255, 255, 255)")
        self.submitStatusLabel.setText("Fill in details to add a new admin...\n* ---> required")

    def validate_data(self):
        '''validate admin data'''
        staff_number = self.staffNumberField.text()
        password = self.passwordField.text()
        confirm_password = self.repeatPasswordField.text()
        first_name = self.firstNameField.text()
        second_name = self.secondNameField.text()
        last_name = self.lastNameField.text()
        position = self.positionField.text()
        status = self.statusField.text()
        error_message = ''
        if staff_number == '':
            error_message += 'Invalid Staff Number...\n'
        if password == '':
            error_message += 'Password cannot be empty...\n'
        if password != confirm_password:
            error_message += 'The passwords entered are not the same...\n'
        if first_name == '':
            error_message += 'Please enter employee first name...\n'
        if last_name == '':
            error_message += 'Please enter employee surname\n'
        if position == '':
            error_message += 'Please enter employee position\n'        
        if error_message != '':
            self.submitStatusLabel.setStyleSheet("padding-left:32px;""color:rgb(255, 0, 0)")
            self.submitStatusLabel.setText(error_message)
            return
        else:
            self.submit_data(staff_number,password,first_name,second_name,last_name,position,status)
    def submit_data(self,staff_number,password,first_name,second_name,last_name,position,status):
        '''submit validated data'''
        password = hashlib.sha256(password.encode()).hexdigest()
        post = None
        post = database.add_admin(staff_number,password,first_name,second_name,last_name,position,status)
        if post is not None:
            self.submitStatusLabel.setStyleSheet("padding-left:32px;""color:rgb(255, 0, 0)")
            self.submitStatusLabel.setText('OOPS! Something went wrong please check your data!!!\n \
        You may have entered an existing staff number')
            return        
        else:
            self.submitStatusLabel.setStyleSheet("padding-left:32px;""color:rgb(0,255,0)")
            self.submitStatusLabel.setText(f'Admin {staff_number} added successfuly!!!') 


    def retranslateUi(self, AddAdminWindow):
        _translate = QtCore.QCoreApplication.translate
        AddAdminWindow.setWindowTitle(_translate("AddAdminWindow", "Add Admin"))
        self.label.setText(_translate("AddAdminWindow", "ADD ADMIN"))
        self.firstNameLabel.setText(_translate("AddAdminWindow", "*First Name:"))
        self.firstNameField.setPlaceholderText(_translate("AddAdminWindow", "Enter First Name"))
        self.secondNameLabel.setText(_translate("AddAdminWindow", "Second Name:"))
        self.secondNameField.setPlaceholderText(_translate("AddAdminWindow", "Enter Second Name"))
        self.lastNameLabel.setText(_translate("AddAdminWindow", "*Last Name:"))
        self.lastNameField.setPlaceholderText(_translate("AddAdminWindow", "Enter Last Name"))
        self.statusLabel.setText(_translate("AddAdminWindow", "Status:"))
        self.statusField.setPlaceholderText(_translate("AddAdminWindow", "Enter employee status"))
        self.positionLabel.setText(_translate("AddAdminWindow", "*Position:"))
        self.positionField.setPlaceholderText(_translate("AddAdminWindow", "Enter employee position"))
        self.staffNumberLabel.setText(_translate("AddAdminWindow", "*Staff Number:"))
        self.staffNumberField.setPlaceholderText(_translate("AddAdminWindow", "Enter your staff number"))
        self.passwordLabel.setText(_translate("AddAdminWindow", "*Password:"))
        self.passwordField.setPlaceholderText(_translate("AddAdminWindow", "Please create a password"))
        self.repeatPasswordLabel.setText(_translate("AddAdminWindow", "*Re-enter password:"))
        self.repeatPasswordField.setPlaceholderText(_translate("AddAdminWindow", "Repeat password"))
        self.clearButton.setText(_translate("AddAdminWindow", "Clear"))
        self.addAdminButton.setText(_translate("AddAdminWindow", "Add Admin"))
import image_resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AddAdminWindow = QtWidgets.QMainWindow()
    ui = Ui_AddAdminWindow()
    ui.setupUi(AddAdminWindow)
    AddAdminWindow.show()
    sys.exit(app.exec_())
