# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dashboard.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from database import Database

database = Database()

class Ui_DashboardWindow(object):
    def setupUi(self, DashboardWindow):
        DashboardWindow.setObjectName("DashboardWindow")
        DashboardWindow.resize(777, 579)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/myicons/other_icons/Bank Building_9.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DashboardWindow.setWindowIcon(icon)
        DashboardWindow.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"font-weight: bold;")
        self.centralwidget = QtWidgets.QWidget(DashboardWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.navigationBarLayout = QtWidgets.QHBoxLayout()
        self.navigationBarLayout.setObjectName("navigationBarLayout")
        self.homeButton = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.homeButton.sizePolicy().hasHeightForWidth())
        self.homeButton.setSizePolicy(sizePolicy)
        self.homeButton.setMinimumSize(QtCore.QSize(80, 0))
        self.homeButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.homeButton.setStyleSheet("QPushButton{\n"
"image:url(:/newPrefix/myicons/common_ui_icons/Home Page_22.png);\n"
"image-position:left;\n"
"border: 2px;\n"
"color:rgb(255, 255, 255);\n"
"border-style : solid;\n"
"padding:4px;\n"
"border-color:rgb(0, 85, 255);\n"
"border-radius:8px;\n"
"}\n"
"QPushButton:pressed{\n"
"border-bottom-color:rgb(0, 196, 113)\n"
"}")
        self.homeButton.setObjectName("homeButton")
        self.navigationBarLayout.addWidget(self.homeButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.navigationBarLayout.addItem(spacerItem)
        self.transactionsButton = QtWidgets.QPushButton(self.widget)
        self.transactionsButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.transactionsButton.setStyleSheet("QPushButton{\n"
"border: 2px;\n"
"color:rgb(255, 255, 255);\n"
"border-style : solid;\n"
"padding:4px;\n"
"border-color:rgb(0, 85, 255);\n"
"border-radius:8px;\n"
"}\n"
"QPushButton:pressed{\n"
"border-bottom-color:rgb(0, 196, 113);\n"
"background-color:rgb(131, 131, 131)\n"
"}")
        self.transactionsButton.setObjectName("transactionsButton")
        self.navigationBarLayout.addWidget(self.transactionsButton)
        self.manageCustomersButton = QtWidgets.QPushButton(self.widget)
        self.manageCustomersButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.manageCustomersButton.setStyleSheet("QPushButton{\n"
"border: 2px;\n"
"color:rgb(255, 255, 255);\n"
"border-style : solid;\n"
"padding:4px;\n"
"border-color:rgb(0, 85, 255);\n"
"border-radius:8px;\n"
"}\n"
"QPushButton:pressed{\n"
"border-bottom-color:rgb(0, 196, 113)\n"
"}")
        self.manageCustomersButton.setObjectName("manageCustomersButton")
        self.navigationBarLayout.addWidget(self.manageCustomersButton)
        self.manageAdminsButton = QtWidgets.QPushButton(self.widget)
        self.manageAdminsButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.manageAdminsButton.setStyleSheet("QPushButton{\n"
"border: 2px;\n"
"color:rgb(255, 255, 255);\n"
"border-style : solid;\n"
"padding:4px;\n"
"border-color:rgb(0, 85, 255);\n"
"border-radius:8px;\n"
"}\n"
"QPushButton:pressed{\n"
"border-bottom-color:rgb(0, 196, 113)\n"
"}")
        self.manageAdminsButton.setObjectName("manageAdminsButton")
        self.navigationBarLayout.addWidget(self.manageAdminsButton)
        self.logoutButton = QtWidgets.QPushButton(self.widget)
        self.logoutButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.logoutButton.setStyleSheet("QPushButton{\n"
"border: 2px;\n"
"color:rgb(255, 255, 255);\n"
"border-style : solid;\n"
"padding:4px;\n"
"border-color:rgb(0, 85, 255);\n"
"border-radius:8px;\n"
"}\n"
"QPushButton:pressed{\n"
"border-bottom-color:rgb(0, 196, 113)\n"
"}")
        self.logoutButton.setObjectName("logoutButton")
        self.navigationBarLayout.addWidget(self.logoutButton)
        self.verticalLayout_2.addLayout(self.navigationBarLayout)
        self.stackedWidget = QtWidgets.QStackedWidget(self.widget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.mainDashboardPage = QtWidgets.QWidget()
        self.mainDashboardPage.setObjectName("mainDashboardPage")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.mainDashboardPage)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label = QtWidgets.QLabel(self.mainDashboardPage)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_9.addWidget(self.label, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.mainDashboardTransactionButton = QtWidgets.QPushButton(self.mainDashboardPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainDashboardTransactionButton.sizePolicy().hasHeightForWidth())
        self.mainDashboardTransactionButton.setSizePolicy(sizePolicy)
        self.mainDashboardTransactionButton.setMinimumSize(QtCore.QSize(248, 120))
        self.mainDashboardTransactionButton.setStyleSheet("QPushButton{\n"
"background-image: url(:/newPrefix/myicons/common_ui_icons/Share Browser Screen_4.png);\n"
"background-repeat: no-repeat;\n"
"background-position: left;\n"
"border: 2px solid;\n"
"color:rgb(0, 0, 0);\n"
"background-color: rgb(0, 196, 172);\n"
"border-color: rgb(0, 0, 0);\n"
"border-radius: 8px;\n"
"padding: 4px;\n"
"padding-left: 48px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:rgb(0, 196, 172) ;\n"
"background-color: rgb(0, 0, 0);\n"
"border-color:rgb(0, 196, 172)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(76, 76, 76);\n"
"}\n"
"")
        self.mainDashboardTransactionButton.setObjectName("mainDashboardTransactionButton")
        self.verticalLayout_3.addWidget(self.mainDashboardTransactionButton, 0, QtCore.Qt.AlignRight)
        self.mainDashboardCustomerManagementButton = QtWidgets.QPushButton(self.mainDashboardPage)
        self.mainDashboardCustomerManagementButton.setMinimumSize(QtCore.QSize(248, 120))
        self.mainDashboardCustomerManagementButton.setStyleSheet("QPushButton{\n"
"background-image: url(:/newPrefix/myicons/common_ui_icons/User Menu Female_43.png);\n"
"background-repeat: no-repeat;\n"
"border: 2px solid;\n"
"color:rgb(0, 0, 0);\n"
"background-color: rgb(0, 196, 172);\n"
"border-color: rgb(0, 0, 0);\n"
"border-radius: 8px;\n"
"padding: 4px;\n"
"padding-left: 48px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:rgb(0, 196, 172) ;\n"
"background-color: rgb(0, 0, 0);\n"
"border-color:rgb(0, 196, 172)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(76, 76, 76);\n"
"}\n"
"")
        self.mainDashboardCustomerManagementButton.setObjectName("mainDashboardCustomerManagementButton")
        self.verticalLayout_3.addWidget(self.mainDashboardCustomerManagementButton, 0, QtCore.Qt.AlignRight)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.mainDashboardAdminManagementButton = QtWidgets.QPushButton(self.mainDashboardPage)
        self.mainDashboardAdminManagementButton.setMinimumSize(QtCore.QSize(248, 120))
        self.mainDashboardAdminManagementButton.setStyleSheet("QPushButton{\n"
"background-image: url(:/newPrefix/myicons/common_ui_icons/Verified account_43.png);\n"
"background-repeat: no-repeat;\n"
"border: 2px solid;\n"
"color:rgb(0, 0, 0);\n"
"background-color: rgb(0, 196, 172);\n"
"border-color: rgb(0, 0, 0);\n"
"border-radius: 8px;\n"
"padding: 4px;\n"
"padding-left: 48px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:rgb(0, 196, 172) ;\n"
"background-color: rgb(0, 0, 0);\n"
"border-color:rgb(0, 196, 172)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(76, 76, 76);\n"
"}\n"
"")
        self.mainDashboardAdminManagementButton.setObjectName("mainDashboardAdminManagementButton")
        self.verticalLayout_8.addWidget(self.mainDashboardAdminManagementButton, 0, QtCore.Qt.AlignLeft)
        self.mainDashboardHelpButton = QtWidgets.QPushButton(self.mainDashboardPage)
        self.mainDashboardHelpButton.setMinimumSize(QtCore.QSize(248, 120))
        self.mainDashboardHelpButton.setStyleSheet("QPushButton{\n"
"background-image: url(:/newPrefix/myicons/common_ui_icons/Help_1.png);\n"
"background-repeat: no-repeat;\n"
"border: 2px solid;\n"
"color:rgb(0, 0, 0);\n"
"background-color: rgb(0, 196, 172);\n"
"border-color: rgb(0, 0, 0);\n"
"border-radius: 8px;\n"
"padding: 4px;\n"
"padding-left: 48px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:rgb(0, 196, 172) ;\n"
"background-color:rgb(53, 53, 53);\n"
"border-color:rgb(0, 196, 172)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(76, 76, 76);\n"
"}\n"
"")
        self.mainDashboardHelpButton.setObjectName("mainDashboardHelpButton")
        self.verticalLayout_8.addWidget(self.mainDashboardHelpButton, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayout_4.addLayout(self.verticalLayout_8)
        self.verticalLayout_9.addLayout(self.horizontalLayout_4)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem2)
        self.stackedWidget.addWidget(self.mainDashboardPage)
        self.transactionsPage = QtWidgets.QWidget()
        self.transactionsPage.setObjectName("transactionsPage")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.transactionsPage)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.transactionsPage)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_6.addWidget(self.label_3)
        self.transactionPageLayout = QtWidgets.QHBoxLayout()
        self.transactionPageLayout.setContentsMargins(16, 16, 16, -1)
        self.transactionPageLayout.setObjectName("transactionPageLayout")
        self.transactionSidePanelLayout = QtWidgets.QVBoxLayout()
        self.transactionSidePanelLayout.setObjectName("transactionSidePanelLayout")
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.transactionSidePanelLayout.addItem(spacerItem3)
        self.transferButton = QtWidgets.QPushButton(self.transactionsPage)
        self.transferButton.setMinimumSize(QtCore.QSize(150, 0))
        self.transferButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.transferButton.setStyleSheet("QPushButton{\n"
"border: 2px solid;\n"
"color:rgb(0, 0, 0);\n"
"background-color: rgb(0, 196, 172);\n"
"border-color: rgb(0, 0, 0);\n"
"border-radius: 8px;\n"
"padding: 4px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:rgb(0, 196, 172) ;\n"
"background-color: rgb(0, 0, 0);\n"
"border-color:rgb(0, 196, 172)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(76, 76, 76);\n"
"}\n"
"")
        self.transferButton.setCheckable(False)
        self.transferButton.setObjectName("transferButton")
        self.transactionSidePanelLayout.addWidget(self.transferButton)
        self.withdrawButton = QtWidgets.QPushButton(self.transactionsPage)
        self.withdrawButton.setMinimumSize(QtCore.QSize(150, 0))
        self.withdrawButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.withdrawButton.setStyleSheet("QPushButton{\n"
"border: 2px solid;\n"
"color:rgb(0, 0, 0);\n"
"background-color: rgb(0, 196, 172);\n"
"border-color: rgb(0, 0, 0);\n"
"border-radius: 8px;\n"
"padding: 4px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:rgb(0, 196, 172) ;\n"
"background-color: rgb(0, 0, 0);\n"
"border-color:rgb(0, 196, 172)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(76, 76, 76);\n"
"}\n"
"")
        self.withdrawButton.setObjectName("withdrawButton")
        self.transactionSidePanelLayout.addWidget(self.withdrawButton)
        self.depositButton = QtWidgets.QPushButton(self.transactionsPage)
        self.depositButton.setMinimumSize(QtCore.QSize(150, 0))
        self.depositButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.depositButton.setStyleSheet("QPushButton{\n"
"border: 2px solid;\n"
"color:rgb(0, 0, 0);\n"
"background-color: rgb(0, 196, 172);\n"
"border-color: rgb(0, 0, 0);\n"
"border-radius: 8px;\n"
"padding: 4px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:rgb(0, 196, 172) ;\n"
"background-color: rgb(0, 0, 0);\n"
"border-color:rgb(0, 196, 172)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(76, 76, 76);\n"
"}\n"
"")
        self.depositButton.setObjectName("depositButton")
        self.transactionSidePanelLayout.addWidget(self.depositButton)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.transactionSidePanelLayout.addItem(spacerItem4)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.transactionSidePanelLayout.addItem(spacerItem5)
        self.transactionPageLayout.addLayout(self.transactionSidePanelLayout)
        spacerItem6 = QtWidgets.QSpacerItem(32, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.transactionPageLayout.addItem(spacerItem6)
        self.transactionFieldsLayout = QtWidgets.QVBoxLayout()
        self.transactionFieldsLayout.setObjectName("transactionFieldsLayout")
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.transactionFieldsLayout.addItem(spacerItem7)
        self.userAccountLabel = QtWidgets.QLabel(self.transactionsPage)
        self.userAccountLabel.setObjectName("userAccountLabel")
        self.transactionFieldsLayout.addWidget(self.userAccountLabel)
        self.senderUserAccountField = QtWidgets.QLineEdit(self.transactionsPage)
        self.senderUserAccountField.setStyleSheet("QLineEdit{\n"
"border: 2px;\n"
"color:rgb(255, 255, 255);\n"
"border-style : solid;\n"
"padding:4px;\n"
"border-color:rgb(0, 85, 255);\n"
"border-radius:8px;\n"
"}\n"
"QLineEdit:focus{\n"
"border-bottom-color:rgb(0, 196, 113)\n"
"}")
        self.senderUserAccountField.setObjectName("senderUserAccountField")
        self.transactionFieldsLayout.addWidget(self.senderUserAccountField)
        self.transactionAmountCurrencyLabel = QtWidgets.QLabel(self.transactionsPage)
        self.transactionAmountCurrencyLabel.setObjectName("transactionAmountCurrencyLabel")
        self.transactionFieldsLayout.addWidget(self.transactionAmountCurrencyLabel)
        self.amountDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.transactionsPage)
        self.amountDoubleSpinBox.setStyleSheet("QDoubleSpinBox{\n"
"border: 2px;\n"
"color:rgb(255, 255, 255);\n"
"border-style : solid;\n"
"padding:4px;\n"
"border-color:rgb(0, 85, 255);\n"
"border-radius:8px;\n"
"}\n"
"QDoubleSpinBox:focus{\n"
"border-bottom-color:rgb(0, 196, 113)\n"
"}")
        self.amountDoubleSpinBox.setMaximum(9999999999999.0)
        self.amountDoubleSpinBox.setObjectName("amountDoubleSpinBox")
        self.transactionFieldsLayout.addWidget(self.amountDoubleSpinBox)
        self.transactionFeeLabel = QtWidgets.QLabel(self.transactionsPage)
        self.transactionFeeLabel.setText("")
        self.transactionFeeLabel.setObjectName("transactionFeeLabel")
        self.transactionFieldsLayout.addWidget(self.transactionFeeLabel)
        self.sourceOfFundsLabel = QtWidgets.QLabel(self.transactionsPage)
        self.sourceOfFundsLabel.setObjectName("sourceOfFundsLabel")
        self.transactionFieldsLayout.addWidget(self.sourceOfFundsLabel)
        self.sourceFundsComboBox = QtWidgets.QComboBox(self.transactionsPage)
        self.sourceFundsComboBox.setStyleSheet("QComboBox{\n"
"border: 2px;\n"
"color:rgb(255, 255, 255);\n"
"border-style : solid;\n"
"padding:4px;\n"
"border-color:rgb(0, 85, 255);\n"
"border-radius:8px;\n"
"}\n"
"QComboBox:focus{\n"
"border-bottom-color:rgb(0, 196, 113)\n"
"}")
        self.sourceFundsComboBox.setObjectName("sourceFundsComboBox")
        self.sourceFundsComboBox.addItem("")
        self.sourceFundsComboBox.addItem("")
        self.sourceFundsComboBox.addItem("")
        self.transactionFieldsLayout.addWidget(self.sourceFundsComboBox)
        self.pinLabel = QtWidgets.QLabel(self.transactionsPage)
        self.pinLabel.setObjectName("pinLabel")
        self.transactionFieldsLayout.addWidget(self.pinLabel)
        self.transactorPINField = QtWidgets.QLineEdit(self.transactionsPage)
        self.transactorPINField.setStyleSheet("QLineEdit{\n"
"border: 2px;\n"
"color:rgb(255, 255, 255);\n"
"border-style : solid;\n"
"padding:4px;\n"
"border-color:rgb(0, 85, 255);\n"
"border-radius:8px;\n"
"}\n"
"QLineEdit:focus{\n"
"border-bottom-color:rgb(0, 196, 113)\n"
"}")
        self.transactorPINField.setMaxLength(26)
        self.transactorPINField.setEchoMode(QtWidgets.QLineEdit.Password)
        self.transactorPINField.setObjectName("transactorPINField")
        self.transactionFieldsLayout.addWidget(self.transactorPINField)
        self.recepientAccountLabel = QtWidgets.QLabel(self.transactionsPage)
        self.recepientAccountLabel.setObjectName("recepientAccountLabel")
        self.transactionFieldsLayout.addWidget(self.recepientAccountLabel)
        self.recepientAccountField = QtWidgets.QLineEdit(self.transactionsPage)
        self.recepientAccountField.setStyleSheet("QLineEdit{\n"
"border: 2px;\n"
"color:rgb(255, 255, 255);\n"
"border-style : solid;\n"
"padding:4px;\n"
"border-color:rgb(0, 85, 255);\n"
"border-radius:8px;\n"
"}\n"
"QLineEdit:focus{\n"
"border-bottom-color:rgb(0, 196, 113)\n"
"}")
        self.recepientAccountField.setObjectName("recepientAccountField")
        self.transactionFieldsLayout.addWidget(self.recepientAccountField)
        self.clearSubmitLayout = QtWidgets.QHBoxLayout()
        self.clearSubmitLayout.setContentsMargins(-1, 10, -1, -1)
        self.clearSubmitLayout.setObjectName("clearSubmitLayout")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.clearSubmitLayout.addItem(spacerItem8)
        self.clearTransactionButton = QtWidgets.QPushButton(self.transactionsPage)
        self.clearTransactionButton.setMinimumSize(QtCore.QSize(80, 0))
        self.clearTransactionButton.setStyleSheet("QPushButton{\n"
"border: 2px solid;\n"
"color:rgb(0, 0, 0);\n"
"background-color: rgb(0, 196, 172);\n"
"border-color: rgb(0, 0, 0);\n"
"border-radius: 8px;\n"
"padding: 4px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:rgb(0, 196, 172) ;\n"
"background-color: rgb(0, 0, 0);\n"
"border-color:rgb(0, 196, 172)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(76, 76, 76);\n"
"}\n"
"")
        self.clearTransactionButton.setObjectName("clearTransactionButton")
        self.clearSubmitLayout.addWidget(self.clearTransactionButton)
        self.submitTransactionButton = QtWidgets.QPushButton(self.transactionsPage)
        self.submitTransactionButton.setMinimumSize(QtCore.QSize(80, 0))
        self.submitTransactionButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.submitTransactionButton.setStyleSheet("QPushButton{\n"
"border: 2px solid;\n"
"color:rgb(0, 0, 0);\n"
"background-color: rgb(0, 196, 172);\n"
"border-color: rgb(0, 0, 0);\n"
"border-radius: 8px;\n"
"padding: 4px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:rgb(0, 196, 172) ;\n"
"background-color: rgb(0, 0, 0);\n"
"border-color:rgb(0, 196, 172)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(76, 76, 76);\n"
"}\n"
"")
        self.submitTransactionButton.setObjectName("submitTransactionButton")
        self.clearSubmitLayout.addWidget(self.submitTransactionButton)
        self.transactionFieldsLayout.addLayout(self.clearSubmitLayout)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.transactionFieldsLayout.addItem(spacerItem9)
        self.successTransactionLabel = QtWidgets.QLabel(self.transactionsPage)
        self.successTransactionLabel.setText("")
        self.successTransactionLabel.setObjectName("successTransactionLabel")
        self.transactionFieldsLayout.addWidget(self.successTransactionLabel)
        self.transactionPageLayout.addLayout(self.transactionFieldsLayout)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.transactionPageLayout.addItem(spacerItem10)
        self.verticalLayout_6.addLayout(self.transactionPageLayout)
        self.stackedWidget.addWidget(self.transactionsPage)
        self.manageCustomersPage = QtWidgets.QWidget()
        self.manageCustomersPage.setObjectName("manageCustomersPage")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.manageCustomersPage)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_4 = QtWidgets.QLabel(self.manageCustomersPage)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_13.addWidget(self.label_4, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_5 = QtWidgets.QLabel(self.manageCustomersPage)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_10.addWidget(self.label_5)
        self.customerIdField = QtWidgets.QLineEdit(self.manageCustomersPage)
        self.customerIdField.setMaximumSize(QtCore.QSize(229, 28))
        self.customerIdField.setStyleSheet("QLineEdit{\n"
"border: 2px;\n"
"color:rgb(255, 255, 255);\n"
"border-style : solid;\n"
"padding:4px;\n"
"border-color:rgb(0, 85, 255);\n"
"border-radius:8px;\n"
"}\n"
"QLineEdit:focus{\n"
"border-bottom-color:rgb(0, 196, 113)\n"
"}")
        self.customerIdField.setMaxLength(30)
        self.customerIdField.setObjectName("customerIdField")
        self.verticalLayout_10.addWidget(self.customerIdField)
        self.label_11 = QtWidgets.QLabel(self.manageCustomersPage)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_10.addWidget(self.label_11)
        self.customerFirstNameField = QtWidgets.QLineEdit(self.manageCustomersPage)
        self.customerFirstNameField.setMaximumSize(QtCore.QSize(229, 28))
        self.customerFirstNameField.setStyleSheet("QLineEdit{\n"
"border: 2px;\n"
"color:rgb(255, 255, 255);\n"
"border-style : solid;\n"
"padding:4px;\n"
"border-color:rgb(0, 85, 255);\n"
"border-radius:8px;\n"
"}\n"
"QLineEdit:focus{\n"
"border-bottom-color:rgb(0, 196, 113)\n"
"}")
        self.customerFirstNameField.setMaxLength(30)
        self.customerFirstNameField.setObjectName("customerFirstNameField")
        self.verticalLayout_10.addWidget(self.customerFirstNameField)
        self.label_12 = QtWidgets.QLabel(self.manageCustomersPage)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_10.addWidget(self.label_12)
        self.customerSecondNameField = QtWidgets.QLineEdit(self.manageCustomersPage)
        self.customerSecondNameField.setMaximumSize(QtCore.QSize(229, 28))
        self.customerSecondNameField.setStyleSheet("QLineEdit{\n"
"border: 2px;\n"
"color:rgb(255, 255, 255);\n"
"border-style : solid;\n"
"padding:4px;\n"
"border-color:rgb(0, 85, 255);\n"
"border-radius:8px;\n"
"}\n"
"QLineEdit:focus{\n"
"border-bottom-color:rgb(0, 196, 113)\n"
"}")
        self.customerSecondNameField.setMaxLength(30)
        self.customerSecondNameField.setObjectName("customerSecondNameField")
        self.verticalLayout_10.addWidget(self.customerSecondNameField)
        self.label_13 = QtWidgets.QLabel(self.manageCustomersPage)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_10.addWidget(self.label_13)
        self.customerLastNameField = QtWidgets.QLineEdit(self.manageCustomersPage)
        self.customerLastNameField.setMaximumSize(QtCore.QSize(229, 28))
        self.customerLastNameField.setStyleSheet("QLineEdit{\n"
"border: 2px;\n"
"color:rgb(255, 255, 255);\n"
"border-style : solid;\n"
"padding:4px;\n"
"border-color:rgb(0, 85, 255);\n"
"border-radius:8px;\n"
"}\n"
"QLineEdit:focus{\n"
"border-bottom-color:rgb(0, 196, 113)\n"
"}")
        self.customerLastNameField.setMaxLength(30)
        self.customerLastNameField.setObjectName("customerLastNameField")
        self.verticalLayout_10.addWidget(self.customerLastNameField)
        self.label_7 = QtWidgets.QLabel(self.manageCustomersPage)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_10.addWidget(self.label_7)
        self.accountTypeComboBox = QtWidgets.QComboBox(self.manageCustomersPage)
        self.accountTypeComboBox.setMaximumSize(QtCore.QSize(229, 28))
        self.accountTypeComboBox.setStyleSheet("QComboBox{\n"
"border: 2px;\n"
"color:rgb(255, 255, 255);\n"
"border-style : solid;\n"
"padding:4px;\n"
"border-color:rgb(0, 85, 255);\n"
"border-radius:8px;\n"
"}\n"
"QComboBox:focus{\n"
"border-bottom-color:rgb(0, 196, 113)\n"
"}")
        self.accountTypeComboBox.setObjectName("accountTypeComboBox")
        self.accountTypeComboBox.addItem("")
        self.accountTypeComboBox.addItem("")
        self.accountTypeComboBox.addItem("")
        self.accountTypeComboBox.addItem("")
        self.verticalLayout_10.addWidget(self.accountTypeComboBox)
        self.label_14 = QtWidgets.QLabel(self.manageCustomersPage)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_10.addWidget(self.label_14)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.manageCustomersPage)
        self.doubleSpinBox.setMaximumSize(QtCore.QSize(229, 28))
        self.doubleSpinBox.setStyleSheet("QDoubleSpinBox{\n"
"border: 2px;\n"
"color:rgb(255, 255, 255);\n"
"border-style : solid;\n"
"padding:4px;\n"
"border-color:rgb(0, 85, 255);\n"
"border-radius:8px;\n"
"}\n"
"QDoubleSpinBox:focus{\n"
"border-bottom-color:rgb(0, 196, 113)\n"
"}")
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.verticalLayout_10.addWidget(self.doubleSpinBox)
        self.customerManagementClearButton = QtWidgets.QPushButton(self.manageCustomersPage)
        self.customerManagementClearButton.setMinimumSize(QtCore.QSize(80, 0))
        self.customerManagementClearButton.setBaseSize(QtCore.QSize(0, 0))
        self.customerManagementClearButton.setStyleSheet("QPushButton{\n"
"border: 2px solid;\n"
"color:rgb(0, 0, 0);\n"
"background-color: rgb(0, 196, 172);\n"
"border-color: rgb(0, 0, 0);\n"
"border-radius: 8px;\n"
"padding: 4px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:rgb(0, 196, 172) ;\n"
"background-color: rgb(0, 0, 0);\n"
"border-color:rgb(0, 196, 172)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(76, 76, 76);\n"
"}\n"
"")
        self.customerManagementClearButton.setObjectName("customerManagementClearButton")
        self.verticalLayout_10.addWidget(self.customerManagementClearButton, 0, QtCore.Qt.AlignRight)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem11)
        self.horizontalLayout_7.addLayout(self.verticalLayout_10)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.customerListTreeView = QtWidgets.QTreeView(self.manageCustomersPage)
        self.customerListTreeView.setMinimumSize(QtCore.QSize(500, 0))
        self.customerListTreeView.setObjectName("customerListTreeView")
        self.verticalLayout_11.addWidget(self.customerListTreeView)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem12)
        self.viewCustomersButton = QtWidgets.QPushButton(self.manageCustomersPage)
        self.viewCustomersButton.setStyleSheet("QPushButton{\n"
"border: 2px solid;\n"
"color:rgb(0, 0, 0);\n"
"background-color: rgb(0, 196, 172);\n"
"border-color: rgb(0, 0, 0);\n"
"border-radius: 8px;\n"
"padding: 4px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:rgb(0, 196, 172) ;\n"
"background-color: rgb(0, 0, 0);\n"
"border-color:rgb(0, 196, 172)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(76, 76, 76);\n"
"}\n"
"")
        self.viewCustomersButton.setObjectName("viewCustomersButton")
        self.horizontalLayout_3.addWidget(self.viewCustomersButton)
        self.createCustomerButton = QtWidgets.QPushButton(self.manageCustomersPage)
        self.createCustomerButton.setStyleSheet("QPushButton{\n"
"border: 2px solid;\n"
"color:rgb(0, 0, 0);\n"
"background-color: rgb(0, 196, 172);\n"
"border-color: rgb(0, 0, 0);\n"
"border-radius: 8px;\n"
"padding: 4px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:rgb(0, 196, 172) ;\n"
"background-color: rgb(0, 0, 0);\n"
"border-color:rgb(0, 196, 172)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(76, 76, 76);\n"
"}\n"
"")
        self.createCustomerButton.setObjectName("createCustomerButton")
        self.horizontalLayout_3.addWidget(self.createCustomerButton)
        self.updateCustomerButton = QtWidgets.QPushButton(self.manageCustomersPage)
        self.updateCustomerButton.setStyleSheet("QPushButton{\n"
"border: 2px solid;\n"
"color:rgb(0, 0, 0);\n"
"background-color: rgb(0, 196, 172);\n"
"border-color: rgb(0, 0, 0);\n"
"border-radius: 8px;\n"
"padding: 4px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:rgb(0, 196, 172) ;\n"
"background-color: rgb(0, 0, 0);\n"
"border-color:rgb(0, 196, 172)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(76, 76, 76);\n"
"}\n"
"")
        self.updateCustomerButton.setObjectName("updateCustomerButton")
        self.horizontalLayout_3.addWidget(self.updateCustomerButton)
        self.deleteCustomerButton = QtWidgets.QPushButton(self.manageCustomersPage)
        self.deleteCustomerButton.setStyleSheet("QPushButton{\n"
"border: 2px solid;\n"
"color:rgb(0, 0, 0);\n"
"background-color: rgb(255, 0, 0);\n"
"border-color: rgb(0, 0, 0);\n"
"border-radius: 8px;\n"
"padding: 4px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:rgb(0, 196, 172) ;\n"
"background-color: rgb(0, 0, 0);\n"
"border-color:rgb(255, 0, 0)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(76, 76, 76);\n"
"}\n"
"")
        self.deleteCustomerButton.setObjectName("deleteCustomerButton")
        self.horizontalLayout_3.addWidget(self.deleteCustomerButton)
        self.verticalLayout_11.addLayout(self.horizontalLayout_3)
        self.updateCustomerStatusLabel = QtWidgets.QLabel(self.manageCustomersPage)
        self.updateCustomerStatusLabel.setText("")
        self.updateCustomerStatusLabel.setObjectName("updateCustomerStatusLabel")
        self.verticalLayout_11.addWidget(self.updateCustomerStatusLabel)
        self.horizontalLayout_7.addLayout(self.verticalLayout_11)
        self.verticalLayout_13.addLayout(self.horizontalLayout_7)
        self.stackedWidget.addWidget(self.manageCustomersPage)
        self.manageAdminsPage = QtWidgets.QWidget()
        self.manageAdminsPage.setObjectName("manageAdminsPage")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.manageAdminsPage)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_2 = QtWidgets.QLabel(self.manageAdminsPage)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_7.addWidget(self.label_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 10, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.staffNumberLabel = QtWidgets.QLabel(self.manageAdminsPage)
        self.staffNumberLabel.setObjectName("staffNumberLabel")
        self.verticalLayout_5.addWidget(self.staffNumberLabel)
        self.staffNumberField = QtWidgets.QLineEdit(self.manageAdminsPage)
        self.staffNumberField.setMaximumSize(QtCore.QSize(254, 28))
        self.staffNumberField.setStyleSheet("QLineEdit{\n"
"border: 2px;\n"
"color:rgb(255, 255, 255);\n"
"border-style : solid;\n"
"padding:4px;\n"
"border-color:rgb(0, 85, 255);\n"
"border-radius:8px;\n"
"}\n"
"QLineEdit:focus{\n"
"border-bottom-color:rgb(0, 196, 113)\n"
"}")
        self.staffNumberField.setMaxLength(26)
        self.staffNumberField.setObjectName("staffNumberField")
        self.verticalLayout_5.addWidget(self.staffNumberField)
        self.firstNameLabel = QtWidgets.QLabel(self.manageAdminsPage)
        self.firstNameLabel.setObjectName("firstNameLabel")
        self.verticalLayout_5.addWidget(self.firstNameLabel)
        self.firstNameField = QtWidgets.QLineEdit(self.manageAdminsPage)
        self.firstNameField.setMaximumSize(QtCore.QSize(254, 28))
        self.firstNameField.setStyleSheet("QLineEdit{\n"
"border: 2px;\n"
"color:rgb(255, 255, 255);\n"
"border-style : solid;\n"
"padding:4px;\n"
"border-color:rgb(0, 85, 255);\n"
"border-radius:8px;\n"
"}\n"
"QLineEdit:focus{\n"
"border-bottom-color:rgb(0, 196, 113)\n"
"}")
        self.firstNameField.setMaxLength(26)
        self.firstNameField.setObjectName("firstNameField")
        self.verticalLayout_5.addWidget(self.firstNameField)
        self.secondNameLabel = QtWidgets.QLabel(self.manageAdminsPage)
        self.secondNameLabel.setObjectName("secondNameLabel")
        self.verticalLayout_5.addWidget(self.secondNameLabel)
        self.secondNameField = QtWidgets.QLineEdit(self.manageAdminsPage)
        self.secondNameField.setMaximumSize(QtCore.QSize(254, 28))
        self.secondNameField.setStyleSheet("QLineEdit{\n"
"border: 2px;\n"
"color:rgb(255, 255, 255);\n"
"border-style : solid;\n"
"padding:4px;\n"
"border-color:rgb(0, 85, 255);\n"
"border-radius:8px;\n"
"}\n"
"QLineEdit:focus{\n"
"border-bottom-color:rgb(0, 196, 113)\n"
"}")
        self.secondNameField.setMaxLength(26)
        self.secondNameField.setObjectName("secondNameField")
        self.verticalLayout_5.addWidget(self.secondNameField)
        self.lastNameLabel = QtWidgets.QLabel(self.manageAdminsPage)
        self.lastNameLabel.setObjectName("lastNameLabel")
        self.verticalLayout_5.addWidget(self.lastNameLabel)
        self.lastNameField = QtWidgets.QLineEdit(self.manageAdminsPage)
        self.lastNameField.setMaximumSize(QtCore.QSize(254, 28))
        self.lastNameField.setStyleSheet("QLineEdit{\n"
"border: 2px;\n"
"color:rgb(255, 255, 255);\n"
"border-style : solid;\n"
"padding:4px;\n"
"border-color:rgb(0, 85, 255);\n"
"border-radius:8px;\n"
"}\n"
"QLineEdit:focus{\n"
"border-bottom-color:rgb(0, 196, 113)\n"
"}")
        self.lastNameField.setMaxLength(26)
        self.lastNameField.setObjectName("lastNameField")
        self.verticalLayout_5.addWidget(self.lastNameField)
        self.statusLabel = QtWidgets.QLabel(self.manageAdminsPage)
        self.statusLabel.setObjectName("statusLabel")
        self.verticalLayout_5.addWidget(self.statusLabel)
        self.statusField = QtWidgets.QLineEdit(self.manageAdminsPage)
        self.statusField.setMaximumSize(QtCore.QSize(254, 28))
        self.statusField.setStyleSheet("QLineEdit{\n"
"border: 2px;\n"
"color:rgb(255, 255, 255);\n"
"border-style : solid;\n"
"padding:4px;\n"
"border-color:rgb(0, 85, 255);\n"
"border-radius:8px;\n"
"}\n"
"QLineEdit:focus{\n"
"border-bottom-color:rgb(0, 196, 113)\n"
"}")
        self.statusField.setMaxLength(26)
        self.statusField.setObjectName("statusField")
        self.verticalLayout_5.addWidget(self.statusField)
        self.positionLabel = QtWidgets.QLabel(self.manageAdminsPage)
        self.positionLabel.setObjectName("positionLabel")
        self.verticalLayout_5.addWidget(self.positionLabel)
        self.adminPositionComboBox = QtWidgets.QComboBox(self.manageAdminsPage)
        self.adminPositionComboBox.setMaximumSize(QtCore.QSize(254, 28))
        self.adminPositionComboBox.setStyleSheet("QComboBox{\n"
"border: 2px;\n"
"color:rgb(255, 255, 255);\n"
"border-style : solid;\n"
"padding:4px;\n"
"border-color:rgb(0, 85, 255);\n"
"border-radius:8px;\n"
"}\n"
"QComboBox:focus{\n"
"border-bottom-color:rgb(0, 196, 113)\n"
"}")
        self.adminPositionComboBox.setObjectName("adminPositionComboBox")
        self.adminPositionComboBox.addItem("")
        self.adminPositionComboBox.addItem("")
        self.adminPositionComboBox.addItem("")
        self.adminPositionComboBox.addItem("")
        self.verticalLayout_5.addWidget(self.adminPositionComboBox)
        self.manageAdminsClearButton = QtWidgets.QPushButton(self.manageAdminsPage)
        self.manageAdminsClearButton.setMinimumSize(QtCore.QSize(80, 0))
        self.manageAdminsClearButton.setStyleSheet("QPushButton{\n"
"border: 2px solid;\n"
"color:rgb(0, 0, 0);\n"
"background-color: rgb(0, 196, 172);\n"
"border-color: rgb(0, 0, 0);\n"
"border-radius: 8px;\n"
"padding: 4px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:rgb(0, 196, 172) ;\n"
"background-color: rgb(0, 0, 0);\n"
"border-color:rgb(0, 196, 172)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(76, 76, 76);\n"
"}\n"
"")
        self.manageAdminsClearButton.setObjectName("manageAdminsClearButton")
        self.verticalLayout_5.addWidget(self.manageAdminsClearButton, 0, QtCore.Qt.AlignRight)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem13)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.adminListTreeView = QtWidgets.QTreeView(self.manageAdminsPage)
        self.adminListTreeView.setMinimumSize(QtCore.QSize(480, 0))
        self.adminListTreeView.setObjectName("adminListTreeView")
        self.verticalLayout_4.addWidget(self.adminListTreeView)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem14)
        self.viewAdminsButton = QtWidgets.QPushButton(self.manageAdminsPage)
        self.viewAdminsButton.setStyleSheet("QPushButton{\n"
"border: 2px solid;\n"
"color:rgb(0, 0, 0);\n"
"background-color: rgb(0, 196, 172);\n"
"border-color: rgb(0, 0, 0);\n"
"border-radius: 8px;\n"
"padding: 4px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:rgb(0, 196, 172) ;\n"
"background-color: rgb(0, 0, 0);\n"
"border-color:rgb(0, 196, 172)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(76, 76, 76);\n"
"}\n"
"")
        self.viewAdminsButton.setObjectName("viewAdminsButton")
        self.horizontalLayout.addWidget(self.viewAdminsButton)
        self.updateAdminButton = QtWidgets.QPushButton(self.manageAdminsPage)
        self.updateAdminButton.setStyleSheet("QPushButton{\n"
"border: 2px solid;\n"
"color:rgb(0, 0, 0);\n"
"background-color: rgb(0, 196, 172);\n"
"border-color: rgb(0, 0, 0);\n"
"border-radius: 8px;\n"
"padding: 4px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:rgb(0, 196, 172) ;\n"
"background-color: rgb(0, 0, 0);\n"
"border-color:rgb(0, 196, 172)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(76, 76, 76);\n"
"}\n"
"")
        self.updateAdminButton.setObjectName("updateAdminButton")
        self.horizontalLayout.addWidget(self.updateAdminButton)
        self.addAdminButton = QtWidgets.QPushButton(self.manageAdminsPage)
        self.addAdminButton.setStyleSheet("QPushButton{\n"
"border: 2px solid;\n"
"color:rgb(0, 0, 0);\n"
"background-color: rgb(0, 196, 172);\n"
"border-color: rgb(0, 0, 0);\n"
"border-radius: 8px;\n"
"padding: 4px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:rgb(0, 196, 172) ;\n"
"background-color: rgb(0, 0, 0);\n"
"border-color:rgb(0, 196, 172)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(76, 76, 76);\n"
"}\n"
"")
        self.addAdminButton.setObjectName("addAdminButton")
        self.horizontalLayout.addWidget(self.addAdminButton, 0, QtCore.Qt.AlignRight)
        self.deleteAdminButton = QtWidgets.QPushButton(self.manageAdminsPage)
        self.deleteAdminButton.setStyleSheet("QPushButton{\n"
"border: 2px solid;\n"
"color:rgb(0, 0, 0);\n"
"background-color: rgb(255, 0, 0);\n"
"border-color: rgb(0, 0, 0);\n"
"border-radius: 8px;\n"
"padding: 4px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:rgb(0, 196, 172) ;\n"
"background-color: rgb(0, 0, 0);\n"
"border-color:rgb(255, 0, 0)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(76, 76, 76);\n"
"}\n"
"")
        self.deleteAdminButton.setObjectName("deleteAdminButton")
        self.horizontalLayout.addWidget(self.deleteAdminButton, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)
        self.stackedWidget.addWidget(self.manageAdminsPage)
        self.verticalLayout_2.addWidget(self.stackedWidget)
        self.verticalLayout.addWidget(self.widget)
        DashboardWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(DashboardWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 777, 21))
        self.menubar.setObjectName("menubar")
        DashboardWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(DashboardWindow)
        self.statusbar.setObjectName("statusbar")
        DashboardWindow.setStatusBar(self.statusbar)

        self.retranslateUi(DashboardWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.logoutButton.clicked.connect(DashboardWindow.close) # type: ignore
        self.homeButton.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(0)) # type: ignore
        self.transactionsButton.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(1)) # type: ignore
        self.manageAdminsButton.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(3)) # type: ignore
        self.manageCustomersButton.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(2)) # type: ignore
        self.mainDashboardTransactionButton.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(1))
        self.mainDashboardCustomerManagementButton.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(2))
        self.mainDashboardAdminManagementButton.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(3))
        self.clearTransactionButton.clicked.connect(self.handle_transaction_clear)
        self.transferButton.clicked.connect(self.handle_transfer_button)
        self.withdrawButton.clicked.connect(self.handle_withdraw_button)
        self.depositButton.clicked.connect(self.handle_deposit_button)
        self.submitTransactionButton.clicked.connect(self.handle_submit_transaction_button)
        QtCore.QMetaObject.connectSlotsByName(DashboardWindow)

    mode = ''

    def handle_transaction_clear(self):
        '''handles clear button on transaction page'''
        self.senderUserAccountField.clear()
        self.amountDoubleSpinBox.setValue(0.0)
        self.recepientAccountField.clear()
        self.sourceFundsComboBox.setCurrentIndex(0)
        self.transactorPINField.clear()
        self.transactionFeeLabel.clear()
        self.transactionFeeLabel.hide()
        self.successTransactionLabel.clear()

    def handle_transfer_button(self):
        '''handles transfer button on transaction page'''
        self.mode = 'transfer'
        self.handle_transaction_clear()
        self.senderUserAccountField.show()
        self.amountDoubleSpinBox.show()
        self.recepientAccountLabel.show()
        self.recepientAccountField.show()
        self.sourceOfFundsLabel.show()
        self.sourceFundsComboBox.show()
        self.transactorPINField.show()
        self.transactionFeeLabel.show()
        self.transactionFeeLabel.hide()
        self.successTransactionLabel.hide()

        return self.mode

    def handle_withdraw_button(self):
        '''handles withdraw button on transaction page'''
        self.mode = 'withdraw'
        self.handle_transaction_clear()
        self.senderUserAccountField.show()
        self.amountDoubleSpinBox.show()
        self.successTransactionLabel.hide()
        self.recepientAccountField.hide()
        self.sourceFundsComboBox.hide()
        self.transactorPINField.show()
        self.transactionFeeLabel.show()
        self.sourceOfFundsLabel.hide()
        self.recepientAccountLabel.hide()
        self.transactionFeeLabel.hide()

        return self.mode

    def handle_deposit_button(self):
        '''handles deposit button on transaction page'''
        self.mode = 'deposit'
        self.handle_transaction_clear()
        self.senderUserAccountField.show()
        self.amountDoubleSpinBox.show()
        self.successTransactionLabel.hide()
        self.recepientAccountField.hide()
        self.sourceFundsComboBox.hide()
        self.transactorPINField.show()
        self.sourceOfFundsLabel.hide()
        self.recepientAccountField.hide()
        self.transactionFeeLabel.show()
        self.transactionFeeLabel.hide()

        return self.mode

    def handle_submit_transaction_button(self):
        '''performs the submit action based on the current transaction mode'''
        if self.mode == 'transfer':
            pass
        elif self.mode == 'withdraw':
            customer_id = self.senderUserAccountField.text()
            amount = self.amountDoubleSpinBox.value()
            if customer_id == '':
                self.transaction_error('Customer ID can not be empty...')
                return
            if amount <= 0:
                self.transaction_error('Withdraw amount must be grater than zero...')
                return
            try:
                result = database.withdraw(customer_id,amount)
                if result == None:
                    balance = database.get_balance(customer_id)
                    self.transaction_success(f'Withdraw Successful !!!\nNew account balance {balance}.')
                else:
                    self.transaction_error('Insufficient account balance')                    
            except:
                self.transaction_error('Wrong User account or PIN')
        elif self.mode == 'deposit':
            customer_id = self.senderUserAccountField.text()
            amount = self.amountDoubleSpinBox.value()
            if customer_id == '':
                self.transaction_error('Customer ID can not be empty...')
                return
            if amount <= 0:
                self.transaction_error('Deposit amount must be grater than zero...')
                return
            try:
                database.deposit(customer_id,amount)
                balance = database.get_balance(customer_id)
                self.transaction_success(f'Deposit Successful !!!\nNew account balance {balance}.')
            except:
                self.transaction_error('Wrong User account or PIN')
        else:
            self.transaction_error('Please choose ( transfer, deposit or withdraw ) !!!')

    def transaction_error(self,message):
        '''displays an error if a transaction doesnt go through'''
        self.successTransactionLabel.setStyleSheet("color:rgb(255,0,0)")
        self.successTransactionLabel.show()
        self.successTransactionLabel.setText(message)

    def transaction_success(self,message):
        '''displays success message if a transactio goes through'''
        self.successTransactionLabel.setStyleSheet("color:rgb(0,255,0)")
        self.successTransactionLabel.show()
        self.successTransactionLabel.setText(message)

    def retranslateUi(self, DashboardWindow):
        _translate = QtCore.QCoreApplication.translate
        DashboardWindow.setWindowTitle(_translate("DashboardWindow", "Main Dashboard"))
        self.homeButton.setText(_translate("DashboardWindow", "HOME"))
        self.transactionsButton.setText(_translate("DashboardWindow", "Transactions "))
        self.manageCustomersButton.setText(_translate("DashboardWindow", "Manage Customers"))
        self.manageAdminsButton.setText(_translate("DashboardWindow", "Manage Admins"))
        self.logoutButton.setText(_translate("DashboardWindow", "Logout"))
        self.label.setText(_translate("DashboardWindow", "MAIN DASHBOARD"))
        self.mainDashboardTransactionButton.setText(_translate("DashboardWindow", "Transaction Management"))
        self.mainDashboardCustomerManagementButton.setText(_translate("DashboardWindow", "Customer Management"))
        self.mainDashboardAdminManagementButton.setText(_translate("DashboardWindow", "Admins Management"))
        self.mainDashboardHelpButton.setText(_translate("DashboardWindow", "Help and Info"))
        self.label_3.setText(_translate("DashboardWindow", "Transactions Page"))
        self.transferButton.setText(_translate("DashboardWindow", "Transfer"))
        self.withdrawButton.setText(_translate("DashboardWindow", "Withdraw"))
        self.depositButton.setText(_translate("DashboardWindow", "Deposit"))
        self.userAccountLabel.setText(_translate("DashboardWindow", "User account:"))
        self.senderUserAccountField.setPlaceholderText(_translate("DashboardWindow", "Please enter your account number"))
        self.transactionAmountCurrencyLabel.setText(_translate("DashboardWindow", "Amount in KSH:"))
        self.sourceOfFundsLabel.setText(_translate("DashboardWindow", "Source of funds:"))
        self.sourceFundsComboBox.setItemText(0, _translate("DashboardWindow", "Your Account"))
        self.sourceFundsComboBox.setItemText(1, _translate("DashboardWindow", "Mpesa"))
        self.sourceFundsComboBox.setItemText(2, _translate("DashboardWindow", "Credit Card"))
        self.pinLabel.setText(_translate("DashboardWindow", "PIN"))
        self.transactorPINField.setPlaceholderText(_translate("DashboardWindow", "Please Enter your PIN"))
        self.recepientAccountLabel.setText(_translate("DashboardWindow", "Recepient Account"))
        self.recepientAccountField.setPlaceholderText(_translate("DashboardWindow", "Enter Recepient\'s account number"))
        self.clearTransactionButton.setText(_translate("DashboardWindow", "Clear"))
        self.submitTransactionButton.setText(_translate("DashboardWindow", "Submit"))
        self.label_4.setText(_translate("DashboardWindow", "Customer Management page"))
        self.label_5.setText(_translate("DashboardWindow", "Customer ID"))
        self.customerIdField.setPlaceholderText(_translate("DashboardWindow", "Please enter Customer\'s ID"))
        self.label_11.setText(_translate("DashboardWindow", "First Name"))
        self.customerFirstNameField.setPlaceholderText(_translate("DashboardWindow", "Please enter First name"))
        self.label_12.setText(_translate("DashboardWindow", "Second Name"))
        self.customerSecondNameField.setPlaceholderText(_translate("DashboardWindow", "Please enter Second name"))
        self.label_13.setText(_translate("DashboardWindow", "Last Name"))
        self.customerLastNameField.setPlaceholderText(_translate("DashboardWindow", "Please enter Last name"))
        self.label_7.setText(_translate("DashboardWindow", "Account Type"))
        self.accountTypeComboBox.setItemText(0, _translate("DashboardWindow", "Comercial Account"))
        self.accountTypeComboBox.setItemText(1, _translate("DashboardWindow", "Locked Savings Account"))
        self.accountTypeComboBox.setItemText(2, _translate("DashboardWindow", "Student\'s Account"))
        self.accountTypeComboBox.setItemText(3, _translate("DashboardWindow", "Fixed Savings Account"))
        self.label_14.setText(_translate("DashboardWindow", "Account Balance"))
        self.customerManagementClearButton.setText(_translate("DashboardWindow", "Clear"))
        self.viewCustomersButton.setText(_translate("DashboardWindow", "View Customers"))
        self.createCustomerButton.setText(_translate("DashboardWindow", "Create Customer"))
        self.updateCustomerButton.setText(_translate("DashboardWindow", "Update customer"))
        self.deleteCustomerButton.setText(_translate("DashboardWindow", "Delete Customer"))
        self.label_2.setText(_translate("DashboardWindow", "MANAGE ADMINS"))
        self.staffNumberLabel.setText(_translate("DashboardWindow", "Staff Number:"))
        self.staffNumberField.setPlaceholderText(_translate("DashboardWindow", "Enter your staff number"))
        self.firstNameLabel.setText(_translate("DashboardWindow", "First Name:"))
        self.firstNameField.setPlaceholderText(_translate("DashboardWindow", "Enter First Name"))
        self.secondNameLabel.setText(_translate("DashboardWindow", "Second Name:"))
        self.secondNameField.setPlaceholderText(_translate("DashboardWindow", "Enter Second Name"))
        self.lastNameLabel.setText(_translate("DashboardWindow", "Last Name:"))
        self.lastNameField.setPlaceholderText(_translate("DashboardWindow", "Enter Last Name"))
        self.statusLabel.setText(_translate("DashboardWindow", "Status:"))
        self.statusField.setPlaceholderText(_translate("DashboardWindow", "Enter employee status"))
        self.positionLabel.setText(_translate("DashboardWindow", "Position:"))
        self.adminPositionComboBox.setItemText(0, _translate("DashboardWindow", "Administrator"))
        self.adminPositionComboBox.setItemText(1, _translate("DashboardWindow", "Network Adminstrator"))
        self.adminPositionComboBox.setItemText(2, _translate("DashboardWindow", "Database Administrator"))
        self.adminPositionComboBox.setItemText(3, _translate("DashboardWindow", "System Administrator"))
        self.manageAdminsClearButton.setText(_translate("DashboardWindow", "Clear"))
        self.viewAdminsButton.setText(_translate("DashboardWindow", "View Admins"))
        self.updateAdminButton.setText(_translate("DashboardWindow", "Update Admin"))
        self.addAdminButton.setText(_translate("DashboardWindow", "Add New Admin"))
        self.deleteAdminButton.setText(_translate("DashboardWindow", "DELETE ADMIN"))
import image_resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DashboardWindow = QtWidgets.QMainWindow()
    ui = Ui_DashboardWindow()
    ui.setupUi(DashboardWindow)
    DashboardWindow.show()
    sys.exit(app.exec_())
