# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dashboard.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DashboardWindow(object):
    def setupUi(self, DashboardWindow):
        DashboardWindow.setObjectName("DashboardWindow")
        DashboardWindow.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/fugue-icons-3.5.6/icons/bank.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DashboardWindow.setWindowIcon(icon)
        DashboardWindow.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"font-weight: bold;")
        self.centralwidget = QtWidgets.QWidget(DashboardWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.navigationBarLayout = QtWidgets.QHBoxLayout()
        self.navigationBarLayout.setObjectName("navigationBarLayout")
        self.homeButton = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.homeButton.sizePolicy().hasHeightForWidth())
        self.homeButton.setSizePolicy(sizePolicy)
        self.homeButton.setMinimumSize(QtCore.QSize(80, 0))
        self.homeButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.homeButton.setStyleSheet("QPushButton{\n"
"image: url(:/newPrefix/fugue-icons-3.5.6/icons/home.png);\n"
"image-position:left;\n"
"border: 2px;\n"
"color:rgb(255, 255, 255);\n"
"border-style : solid;\n"
"padding:4px;\n"
"border-color:rgb(0, 85, 255);\n"
"border-radius:8px;\n"
"}\n"
"QPushButton:pressed{\n"
"border-bottom-color:rgb(0, 196, 113)\n"
"}")
        self.homeButton.setObjectName("homeButton")
        self.navigationBarLayout.addWidget(self.homeButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.navigationBarLayout.addItem(spacerItem)
        self.transactionsButton = QtWidgets.QPushButton(self.widget)
        self.transactionsButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.transactionsButton.setStyleSheet("QPushButton{\n"
"border: 2px;\n"
"color:rgb(255, 255, 255);\n"
"border-style : solid;\n"
"padding:4px;\n"
"border-color:rgb(0, 85, 255);\n"
"border-radius:8px;\n"
"}\n"
"QPushButton:pressed{\n"
"border-bottom-color:rgb(0, 196, 113)\n"
"}")
        self.transactionsButton.setObjectName("transactionsButton")
        self.navigationBarLayout.addWidget(self.transactionsButton)
        self.manageCustomersButton = QtWidgets.QPushButton(self.widget)
        self.manageCustomersButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.manageCustomersButton.setStyleSheet("QPushButton{\n"
"border: 2px;\n"
"color:rgb(255, 255, 255);\n"
"border-style : solid;\n"
"padding:4px;\n"
"border-color:rgb(0, 85, 255);\n"
"border-radius:8px;\n"
"}\n"
"QPushButton:pressed{\n"
"border-bottom-color:rgb(0, 196, 113)\n"
"}")
        self.manageCustomersButton.setObjectName("manageCustomersButton")
        self.navigationBarLayout.addWidget(self.manageCustomersButton)
        self.manageAdminsButton = QtWidgets.QPushButton(self.widget)
        self.manageAdminsButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.manageAdminsButton.setStyleSheet("QPushButton{\n"
"border: 2px;\n"
"color:rgb(255, 255, 255);\n"
"border-style : solid;\n"
"padding:4px;\n"
"border-color:rgb(0, 85, 255);\n"
"border-radius:8px;\n"
"}\n"
"QPushButton:pressed{\n"
"border-bottom-color:rgb(0, 196, 113)\n"
"}")
        self.manageAdminsButton.setObjectName("manageAdminsButton")
        self.navigationBarLayout.addWidget(self.manageAdminsButton)
        self.logoutButton = QtWidgets.QPushButton(self.widget)
        self.logoutButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.logoutButton.setStyleSheet("QPushButton{\n"
"border: 2px;\n"
"color:rgb(255, 255, 255);\n"
"border-style : solid;\n"
"padding:4px;\n"
"border-color:rgb(0, 85, 255);\n"
"border-radius:8px;\n"
"}\n"
"QPushButton:pressed{\n"
"border-bottom-color:rgb(0, 196, 113)\n"
"}")
        self.logoutButton.setObjectName("logoutButton")
        self.navigationBarLayout.addWidget(self.logoutButton)
        self.verticalLayout_2.addLayout(self.navigationBarLayout)
        self.stackedWidget = QtWidgets.QStackedWidget(self.widget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.mainDashboardPage = QtWidgets.QWidget()
        self.mainDashboardPage.setObjectName("mainDashboardPage")
        self.label = QtWidgets.QLabel(self.mainDashboardPage)
        self.label.setGeometry(QtCore.QRect(9, 9, 199, 25))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.mainDashboardPage)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(140, 220, 160, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.stackedWidget.addWidget(self.mainDashboardPage)
        self.transactionsPage = QtWidgets.QWidget()
        self.transactionsPage.setObjectName("transactionsPage")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.transactionsPage)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.transactionsPage)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_6.addWidget(self.label_3)
        self.transactionPageLayout = QtWidgets.QHBoxLayout()
        self.transactionPageLayout.setContentsMargins(16, 16, 16, -1)
        self.transactionPageLayout.setObjectName("transactionPageLayout")
        self.transactionSidePanelLayout = QtWidgets.QVBoxLayout()
        self.transactionSidePanelLayout.setObjectName("transactionSidePanelLayout")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.transactionSidePanelLayout.addItem(spacerItem1)
        self.transferButton = QtWidgets.QPushButton(self.transactionsPage)
        self.transferButton.setMinimumSize(QtCore.QSize(150, 0))
        self.transferButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.transferButton.setStyleSheet("QPushButton{\n"
"border: 2px solid;\n"
"color:rgb(0, 0, 0);\n"
"border-color: rgb(136, 23, 152);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 8px;\n"
"padding: 4px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color: rgb(1, 18, 255);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(0, 0, 0);\n"
"}\n"
"QPushButton:focus{\n"
"background-color: rgb(159, 159, 159);\n"
"}\n"
"")
        self.transferButton.setCheckable(False)
        self.transferButton.setObjectName("transferButton")
        self.transactionSidePanelLayout.addWidget(self.transferButton)
        self.withdrawButton = QtWidgets.QPushButton(self.transactionsPage)
        self.withdrawButton.setMinimumSize(QtCore.QSize(150, 0))
        self.withdrawButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.withdrawButton.setStyleSheet("QPushButton{\n"
"border: 2px solid;\n"
"color:rgb(0, 0, 0);\n"
"border-color: rgb(136, 23, 152);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 8px;\n"
"padding: 4px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color: rgb(1, 18, 255);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(0, 0, 0);\n"
"}\n"
"QPushButton:focus{\n"
"background-color: rgb(159, 159, 159);\n"
"}\n"
"")
        self.withdrawButton.setObjectName("withdrawButton")
        self.transactionSidePanelLayout.addWidget(self.withdrawButton)
        self.depositButton = QtWidgets.QPushButton(self.transactionsPage)
        self.depositButton.setMinimumSize(QtCore.QSize(150, 0))
        self.depositButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.depositButton.setStyleSheet("QPushButton{\n"
"border: 2px solid;\n"
"color:rgb(0, 0, 0);\n"
"border-color: rgb(136, 23, 152);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 8px;\n"
"padding: 4px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color: rgb(1, 18, 255);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(0, 0, 0);\n"
"}\n"
"QPushButton:focus{\n"
"background-color: rgb(159, 159, 159);\n"
"}\n"
"")
        self.depositButton.setObjectName("depositButton")
        self.transactionSidePanelLayout.addWidget(self.depositButton)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.transactionSidePanelLayout.addItem(spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.transactionSidePanelLayout.addItem(spacerItem3)
        self.transactionPageLayout.addLayout(self.transactionSidePanelLayout)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.transactionPageLayout.addItem(spacerItem4)
        self.transactionFieldsLayout = QtWidgets.QVBoxLayout()
        self.transactionFieldsLayout.setObjectName("transactionFieldsLayout")
        self.label_6 = QtWidgets.QLabel(self.transactionsPage)
        self.label_6.setObjectName("label_6")
        self.transactionFieldsLayout.addWidget(self.label_6)
        self.senderUserAccountField = QtWidgets.QLineEdit(self.transactionsPage)
        self.senderUserAccountField.setStyleSheet("QLineEdit{\n"
"border: 2px;\n"
"color:rgb(255, 255, 255);\n"
"border-style : solid;\n"
"padding:4px;\n"
"border-color:rgb(0, 85, 255);\n"
"border-radius:8px;\n"
"}\n"
"QLineEdit:focus{\n"
"border-bottom-color:rgb(0, 196, 113)\n"
"}")
        self.senderUserAccountField.setObjectName("senderUserAccountField")
        self.transactionFieldsLayout.addWidget(self.senderUserAccountField)
        self.transactionAmounLabel = QtWidgets.QLabel(self.transactionsPage)
        self.transactionAmounLabel.setObjectName("transactionAmounLabel")
        self.transactionFieldsLayout.addWidget(self.transactionAmounLabel)
        self.amountDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.transactionsPage)
        self.amountDoubleSpinBox.setStyleSheet("QDoubleSpinBox{\n"
"border: 2px;\n"
"color:rgb(255, 255, 255);\n"
"border-style : solid;\n"
"padding:4px;\n"
"border-color:rgb(0, 85, 255);\n"
"border-radius:8px;\n"
"}\n"
"QDoubleSpinBox:focus{\n"
"border-bottom-color:rgb(0, 196, 113)\n"
"}")
        self.amountDoubleSpinBox.setMaximum(9999999999999.0)
        self.amountDoubleSpinBox.setObjectName("amountDoubleSpinBox")
        self.transactionFieldsLayout.addWidget(self.amountDoubleSpinBox)
        self.transactionFeeLabel = QtWidgets.QLabel(self.transactionsPage)
        self.transactionFeeLabel.setText("")
        self.transactionFeeLabel.setObjectName("transactionFeeLabel")
        self.transactionFieldsLayout.addWidget(self.transactionFeeLabel)
        self.label_8 = QtWidgets.QLabel(self.transactionsPage)
        self.label_8.setObjectName("label_8")
        self.transactionFieldsLayout.addWidget(self.label_8)
        self.sourceFundsComboBox = QtWidgets.QComboBox(self.transactionsPage)
        self.sourceFundsComboBox.setStyleSheet("QComboBox{\n"
"border: 2px;\n"
"color:rgb(255, 255, 255);\n"
"border-style : solid;\n"
"padding:4px;\n"
"border-color:rgb(0, 85, 255);\n"
"border-radius:8px;\n"
"}\n"
"QComboBox:focus{\n"
"border-bottom-color:rgb(0, 196, 113)\n"
"}")
        self.sourceFundsComboBox.setObjectName("sourceFundsComboBox")
        self.sourceFundsComboBox.addItem("")
        self.sourceFundsComboBox.addItem("")
        self.sourceFundsComboBox.addItem("")
        self.transactionFieldsLayout.addWidget(self.sourceFundsComboBox)
        self.label_9 = QtWidgets.QLabel(self.transactionsPage)
        self.label_9.setObjectName("label_9")
        self.transactionFieldsLayout.addWidget(self.label_9)
        self.transactorPINField = QtWidgets.QLineEdit(self.transactionsPage)
        self.transactorPINField.setStyleSheet("QLineEdit{\n"
"border: 2px;\n"
"color:rgb(255, 255, 255);\n"
"border-style : solid;\n"
"padding:4px;\n"
"border-color:rgb(0, 85, 255);\n"
"border-radius:8px;\n"
"}\n"
"QLineEdit:focus{\n"
"border-bottom-color:rgb(0, 196, 113)\n"
"}")
        self.transactorPINField.setMaxLength(26)
        self.transactorPINField.setEchoMode(QtWidgets.QLineEdit.Password)
        self.transactorPINField.setObjectName("transactorPINField")
        self.transactionFieldsLayout.addWidget(self.transactorPINField)
        self.label_10 = QtWidgets.QLabel(self.transactionsPage)
        self.label_10.setObjectName("label_10")
        self.transactionFieldsLayout.addWidget(self.label_10)
        self.recepientAccountField = QtWidgets.QLineEdit(self.transactionsPage)
        self.recepientAccountField.setStyleSheet("QLineEdit{\n"
"border: 2px;\n"
"color:rgb(255, 255, 255);\n"
"border-style : solid;\n"
"padding:4px;\n"
"border-color:rgb(0, 85, 255);\n"
"border-radius:8px;\n"
"}\n"
"QLineEdit:focus{\n"
"border-bottom-color:rgb(0, 196, 113)\n"
"}")
        self.recepientAccountField.setObjectName("recepientAccountField")
        self.transactionFieldsLayout.addWidget(self.recepientAccountField)
        self.clearSubmitLayout = QtWidgets.QHBoxLayout()
        self.clearSubmitLayout.setContentsMargins(-1, 10, -1, -1)
        self.clearSubmitLayout.setObjectName("clearSubmitLayout")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.clearSubmitLayout.addItem(spacerItem5)
        self.clearTransactionButton = QtWidgets.QPushButton(self.transactionsPage)
        self.clearTransactionButton.setMinimumSize(QtCore.QSize(80, 0))
        self.clearTransactionButton.setStyleSheet("QPushButton{\n"
"border: 2px solid;\n"
"color:rgb(0, 0, 0);\n"
"border-color: rgb(136, 23, 152);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 8px;\n"
"padding: 4px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color: rgb(1, 18, 255);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(0, 0, 0);\n"
"}\n"
"")
        self.clearTransactionButton.setObjectName("clearTransactionButton")
        self.clearSubmitLayout.addWidget(self.clearTransactionButton)
        self.submitTransactionButton = QtWidgets.QPushButton(self.transactionsPage)
        self.submitTransactionButton.setMinimumSize(QtCore.QSize(80, 0))
        self.submitTransactionButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.submitTransactionButton.setStyleSheet("QPushButton{\n"
"border: 2px solid;\n"
"color:rgb(0, 0, 0);\n"
"border-color: rgb(136, 23, 152);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 8px;\n"
"padding: 4px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color: rgb(1, 18, 255);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(0, 0, 0);\n"
"}\n"
"")
        self.submitTransactionButton.setObjectName("submitTransactionButton")
        self.clearSubmitLayout.addWidget(self.submitTransactionButton)
        self.transactionFieldsLayout.addLayout(self.clearSubmitLayout)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.transactionFieldsLayout.addItem(spacerItem6)
        self.successTransactionLabel = QtWidgets.QLabel(self.transactionsPage)
        self.successTransactionLabel.setText("")
        self.successTransactionLabel.setObjectName("successTransactionLabel")
        self.transactionFieldsLayout.addWidget(self.successTransactionLabel)
        self.transactionPageLayout.addLayout(self.transactionFieldsLayout)
        self.verticalLayout_6.addLayout(self.transactionPageLayout)
        self.stackedWidget.addWidget(self.transactionsPage)
        self.manageAdminsPage = QtWidgets.QWidget()
        self.manageAdminsPage.setObjectName("manageAdminsPage")
        self.label_2 = QtWidgets.QLabel(self.manageAdminsPage)
        self.label_2.setGeometry(QtCore.QRect(9, 9, 186, 25))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pushButton_6 = QtWidgets.QPushButton(self.manageAdminsPage)
        self.pushButton_6.setGeometry(QtCore.QRect(210, 210, 75, 21))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.manageAdminsPage)
        self.pushButton_7.setGeometry(QtCore.QRect(110, 260, 75, 23))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.manageAdminsPage)
        self.pushButton_8.setGeometry(QtCore.QRect(50, 210, 75, 23))
        self.pushButton_8.setObjectName("pushButton_8")
        self.treeView = QtWidgets.QTreeView(self.manageAdminsPage)
        self.treeView.setGeometry(QtCore.QRect(410, 130, 256, 192))
        self.treeView.setObjectName("treeView")
        self.stackedWidget.addWidget(self.manageAdminsPage)
        self.verticalLayout_2.addWidget(self.stackedWidget)
        self.verticalLayout.addWidget(self.widget)
        DashboardWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(DashboardWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        DashboardWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(DashboardWindow)
        self.statusbar.setObjectName("statusbar")
        DashboardWindow.setStatusBar(self.statusbar)

        self.retranslateUi(DashboardWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.homeButton.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(0)) # type: ignore
        self.logoutButton.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(0)) # type: ignore
        self.manageAdminsButton.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(2)) # type: ignore
        self.manageCustomersButton.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(0)) # type: ignore
        self.transactionsButton.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(1)) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DashboardWindow)

    def retranslateUi(self, DashboardWindow):
        _translate = QtCore.QCoreApplication.translate
        DashboardWindow.setWindowTitle(_translate("DashboardWindow", "Main Dashboard"))
        self.homeButton.setText(_translate("DashboardWindow", "HOME"))
        self.transactionsButton.setText(_translate("DashboardWindow", "Transactions "))
        self.manageCustomersButton.setText(_translate("DashboardWindow", "Manage Customers"))
        self.manageAdminsButton.setText(_translate("DashboardWindow", "Manage Admins"))
        self.logoutButton.setText(_translate("DashboardWindow", "Logout"))
        self.label.setText(_translate("DashboardWindow", "MAIN DASHBOARD"))
        self.label_3.setText(_translate("DashboardWindow", "Transactions Page"))
        self.transferButton.setText(_translate("DashboardWindow", "Transfer"))
        self.withdrawButton.setText(_translate("DashboardWindow", "Withdraw"))
        self.depositButton.setText(_translate("DashboardWindow", "Deposit"))
        self.label_6.setText(_translate("DashboardWindow", "User account:"))
        self.senderUserAccountField.setPlaceholderText(_translate("DashboardWindow", "Please enter your account number"))
        self.transactionAmounLabel.setText(_translate("DashboardWindow", "Amount in KSH:"))
        self.label_8.setText(_translate("DashboardWindow", "Source of funds:"))
        self.sourceFundsComboBox.setItemText(0, _translate("DashboardWindow", "Your Account"))
        self.sourceFundsComboBox.setItemText(1, _translate("DashboardWindow", "Mpesa"))
        self.sourceFundsComboBox.setItemText(2, _translate("DashboardWindow", "Credit Card"))
        self.label_9.setText(_translate("DashboardWindow", "PIN"))
        self.transactorPINField.setPlaceholderText(_translate("DashboardWindow", "Please Enter your PIN"))
        self.label_10.setText(_translate("DashboardWindow", "Recepient Account"))
        self.recepientAccountField.setPlaceholderText(_translate("DashboardWindow", "Please enter Recepient\'s account number"))
        self.clearTransactionButton.setText(_translate("DashboardWindow", "Clear"))
        self.submitTransactionButton.setText(_translate("DashboardWindow", "Submit"))
        self.label_2.setText(_translate("DashboardWindow", "MANAGE ADMINS"))
        self.pushButton_6.setText(_translate("DashboardWindow", "Add Admin"))
        self.pushButton_7.setText(_translate("DashboardWindow", "UPDATE ADMINS"))
        self.pushButton_8.setText(_translate("DashboardWindow", "DELETE ADMIN"))
import image_resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DashboardWindow = QtWidgets.QMainWindow()
    ui = Ui_DashboardWindow()
    ui.setupUi(DashboardWindow)
    DashboardWindow.show()
    sys.exit(app.exec_())
