# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import hashlib
from database import Database
import add_admin
database = Database()

class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(800, 600)
        LoginWindow.setMinimumSize(QtCore.QSize(800, 600))
        LoginWindow.setMaximumSize(QtCore.QSize(800, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/fugue-icons-3.5.6/icons/user-business.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        LoginWindow.setWindowIcon(icon)
        LoginWindow.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color:rgb(255,255,255);\n"
"font-weight:bold")
        self.centralwidget = QtWidgets.QWidget(LoginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setMinimumSize(QtCore.QSize(782, 541))
        self.widget.setMaximumSize(QtCore.QSize(782, 541))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 1, 1, 1, QtCore.Qt.AlignHCenter)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 1, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 2, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color:rgb(255, 255, 255)")
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.staffNumberField = QtWidgets.QLineEdit(self.widget)
        self.staffNumberField.setMinimumSize(QtCore.QSize(0, 30))
        self.staffNumberField.setStyleSheet("QLineEdit{\n"
"border: 4px;\n"
"color:rgb(255, 255, 255);\n"
"border-style : solid;\n"
"padding-left:6px;\n"
"border-color:rgb(0, 85, 255);\n"
"border-radius:8px;\n"
"}\n"
"QLineEdit:focus{\n"
"border-bottom-color:rgb(0, 196, 113)\n"
"}")
        self.staffNumberField.setMaxLength(30)
        self.staffNumberField.setObjectName("staffNumberField")
        self.verticalLayout_2.addWidget(self.staffNumberField)
        spacerItem3 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_2.addItem(spacerItem3)
        self.label_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.passwordField = QtWidgets.QLineEdit(self.widget)
        self.passwordField.setMinimumSize(QtCore.QSize(0, 30))
        self.passwordField.setStyleSheet("QLineEdit{\n"
"border: 4px;\n"
"color:rgb(255, 255, 255);\n"
"border-style : solid;\n"
"padding-left:6px;\n"
"border-color:rgb(0, 85, 255);\n"
"border-radius:8px;\n"
"}\n"
"QLineEdit:focus{\n"
"border-bottom-color:rgb(0, 196, 113)\n"
"}")
        self.passwordField.setMaxLength(30)
        self.passwordField.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordField.setObjectName("passwordField")
        self.verticalLayout_2.addWidget(self.passwordField)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.loginButton = QtWidgets.QPushButton(self.widget)
        self.loginButton.setMinimumSize(QtCore.QSize(200, 30))
        self.loginButton.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.loginButton.setFont(font)
        self.loginButton.setStyleSheet("QPushButton{\n"
"color:rgb(255, 255, 255);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.948864, y2:0.949, stop:0 rgba(0, 255, 0, 255), stop:0.0227273 rgba(0, 95, 0, 255), stop:0.988636 rgba(0, 255, 180, 255));\n"
"border: 2px;\n"
"border-style : solid;\n"
"border-radius:8px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:rgb(85, 0, 255)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"color:rgb(85, 0, 255);\n"
"    background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 170, 127, 255), stop:0.551136 rgba(0, 198, 145, 255), stop:0.98 rgba(0, 232, 170, 255), stop:1 rgba(0, 0, 0, 0));\n"
"}")
        self.loginButton.setObjectName("loginButton")
        self.verticalLayout_2.addWidget(self.loginButton, 0, QtCore.Qt.AlignHCenter)
        self.gridLayout.addLayout(self.verticalLayout_2, 2, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem5, 3, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setStyleSheet("\n"
"color: rgb(255, 0, 0);")
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 1, 1, 2, QtCore.Qt.AlignLeft)
        self.loginStatusLabel = QtWidgets.QLabel(self.widget)
        self.loginStatusLabel.setStyleSheet("padding-left: 24px;")
        self.loginStatusLabel.setText("")
        self.loginStatusLabel.setObjectName("loginStatusLabel")
        self.gridLayout.addWidget(self.loginStatusLabel, 1, 0, 1, 1, QtCore.Qt.AlignTop)
        self.verticalLayout.addWidget(self.widget)
        LoginWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(LoginWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        LoginWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(LoginWindow)
        self.statusbar.setObjectName("statusbar")
        LoginWindow.setStatusBar(self.statusbar)

        self.loginButton.clicked.connect(self.login)
        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def login(self):
        '''checks whether provided details are correct'''
        staff_number = self.staffNumberField.text()
        password = self.passwordField.text()
        password = hashlib.sha256(password.encode()).hexdigest()
        post = database.get_admin(staff_number,password) 
        # print (post)
        # print(f'length post :{len(post)}')
        if post == None:
            self.loginStatusLabel.setStyleSheet("color:rgb(255,0,0)")
            self.loginStatusLabel.setText('Invalid Login credentials entered !!!')
        elif len(post) > 0 :
            self.loginStatusLabel.setStyleSheet("color:rgb(0,255,0)")
            self.loginStatusLabel.setText('Login successful, Launching app...')
            self.AddAdminWindow = QtWidgets.QMainWindow()
            ui_to_call = add_admin.Ui_AddAdminWindow()
            ui_to_call.setupUi(self.AddAdminWindow)
            self.AddAdminWindow.show()
            LoginWindow.close()     
        else:
            self.loginStatusLabel.setStyleSheet("color:rgb(255,0,0)")
            self.loginStatusLabel.setText('Something went wrong')

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "ADMIN LOGIN"))
        self.label_3.setText(_translate("LoginWindow", "ADMIN LOGIN"))
        self.label.setText(_translate("LoginWindow", "Staff number"))
        self.staffNumberField.setPlaceholderText(_translate("LoginWindow", "Please enter your staff number"))
        self.label_2.setText(_translate("LoginWindow", "Password"))
        self.passwordField.setPlaceholderText(_translate("LoginWindow", "Please enter your password"))
        self.loginButton.setText(_translate("LoginWindow", "LOGIN"))
        self.label_4.setText(_translate("LoginWindow", "PAGE FOR ADMINS ONLY !!!! ALL ACTIONS ARE MONITERED"))
import image_resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoginWindow = QtWidgets.QMainWindow()
    ui = Ui_LoginWindow()
    ui.setupUi(LoginWindow)
    LoginWindow.show()
    sys.exit(app.exec_())
